baseURL = 'https://rodaine.com/'
languageCode = 'en-us'
title = 'Rodaine'
enableGitInfo = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
footnoteReturnLinkContents = "↑"
disableKinds = ["taxonomy", "term"]

[pagination]
pagerSize = 5

[markup.highlight]
noClasses = false

[markup.goldmark]
parser.attribute.block = true
renderer.unsafe = true

[permalinks]
posts = '/:year/:month/:slug/'
til = '/til/:year/:month/:slug/'

[frontmatter]
date = [':filename', ':default']
lastmod = [':git', ':fileModTime', ':filename', ':default']
publishDate = [':filename', ':default']
