# OVERRIDES SET BY GITHUB
# safe: true
# lsi: false
# pygments: true
# source: <your pages repo>
# destination: <the build dir>

#SITE SETTINGS
name: "Rodaine"
url: "http://www.rodaine.com"
description: "Chris Roche blogs about web development and the questionably finer things in life."
keywords: "chris, roche, web, development"
contact: "rodaine@gmail.com"

#SERVER SETTINGS
auto: true
server: true

#RENDERING
markdown: maruku
pygments: true
permalink: /:year/:month/:title/
paginate: 1
paginate_path: 'page/:num'
future: false

#NAVIGATION
nav:
 - 
  url: "/index.html"
  icon: "icon-home"
  text: "Home"
 - 
  url: "/chris-roche/index.html"
  icon: "icon-user"
  text: ' Chris Roche'

#EXCLUSIONS / INCLUSIONS
exclude: README.md, codekit-config.json, config.rb, CNAME
