#SITE SETTINGS
name:        "Rodaine"
me:          "Chris Roche"
url:         "https://rodaine.com"
description: "In which Chris Roche blogs about web development and the questionably finer things in life."
keywords:    "chris, roche, web, development, rodaine"

#CONTACT / SOCIAL INFO
email:       "rodaine@gmail.com"
twitter:     "@rodaine"
facebook:    "2057767"
disqus:      "rodaine"
username:    "rodaine"

#RENDERING
highlighter: null
markdown:    kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

permalink: "/:year/:month/:title/"
future:    false

#PAGINATION
paginate:       5
paginate_path:  "page/:num"
paginate_items: 5

#PLUGINS AND EXTENSIONS
plugins:
 - jekyll-sitemap
 - jekyll-paginate

sass:
  sass_dir: _resources/scss
  style:    :compressed

#EXCLUSIONS / INCLUSIONS
exclude:
 - CNAME
 - config.rb
 - Gemfile
 - Gemfile.lock
 - Gruntfile.coffee
 - LICENSE.md
 - node_modules
 - package.json
 - README.md
 - rodaine.com.sublime-project
 - script
 - vendor
