#SITE SETTINGS
name:        "Rodaine"
me:          "Chris Roche"
url:         "http://www.rodaine.com"
description: "In which Chris Roche blogs about web development and the questionably finer things in life."
keywords:    "chris, roche, web, development, rodaine"

#CONTACT / SOCIAL INFO
email:       "rodaine@gmail.com"
twitter:     "@rodaine"
facebook:    "2057767"

#RENDERING
markdown: rdiscount
rdiscount:
  extensions: [smart]

drafts:    false
permalink: "/:year/:month/:title/"
future:    false

#PAGINATION
paginate:      5
paginate_path: "page/:num"
paginate_items: 5

#EXCLUSIONS / INCLUSIONS
exclude:
 - README.md
 - codekit-config.json
 - config.rb
 - CNAME
 - rodaine.com.sublime-project
 - rodaine.com.sublime-workspace
 - node_modules
 - Gruntfile.coffee
 - package.json
