# SITE SETTINGS
name: "Rodaine"
me: "Chris Roche"
url: "https://rodaine.com"
description: "In which Chris Roche blogs about software development and the questionably finer things in life."
keywords: "chris, roche, web, software, development, rodaine"

# CONTACT / SOCIAL INFO
email: "chris@rodaine.com"
twitter: "@rodaine"
facebook: "2057767"
username: "rodaine"

# COLLECTIONS
collections:
  - talks

# RENDERING
highlighter: null
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
sass:
  sass_dir: _resources/scss
  style: :compressed

permalink: "/:year/:month/:title/"
future: false

# PAGINATION
paginate: 5
paginate_path: "page/:num"
paginate_items: 5

#PLUGINS AND EXTENSIONS
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-commonmark-ghpages

#FRONT MATTER DEFAULT VALUES
defaults:
  - # no sitemap entry for pagination pages (already marked as no-index)
    scope:
      path: "page"
    values:
      sitemap: false

#EXCLUSIONS / INCLUSIONS
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - LICENSE.md
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - script
  - tsconfig.json
  - tslint.json
  - vendor
  - webpack.config.js
