name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: gem install pkg-config bundler
    - run: gem install nokogiri -v '1.10.4' --source 'https://rubygems.org/'
