name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Setup Bundler
      run: gem install bundler -v 2.2.17
    - name: Bootstrap
      run: make bootstrap
    - name: Build
      run: make build
